// Drive! and Fly! on a phone: the goal chip and the steer hint stay in the sky, clear of the road, Amelia, the caption, the map and each other.
module.exports=async({pg,S,W})=>{const act=t=>pg.evaluate(t=>{const b=[...document.querySelectorAll('#actions .act')].find(b=>b.textContent.includes(t));b&&b.click();return !!b;},t);
await pg.click('#go');await W(2000);await pg.click('.th[data-id="earth"]');await W(2500);if(await pg.isVisible('.th[data-id="earth"]'))await pg.click('.th[data-id="earth"]');await W(11000);
const boxes=()=>pg.evaluate(()=>Object.fromEntries(['#goalchip','#flyhint','#caption','#minimap','#pill','#tstars','#bottom'].map(s=>{const e=document.querySelector(s);if(!e||e.hidden||!e.offsetParent&&getComputedStyle(e).position!=='fixed'||!e.textContent&&s==='#caption')return [s,null];const r=e.getBoundingClientRect();return [s,r.width?{l:r.left,t:r.top,r:r.right,b:r.bottom}:null]})));
const hit=(a,b)=>a&&b&&a.l<b.r-1&&b.l<a.r-1&&a.t<b.b-1&&b.t<a.b-1;
for(const mode of ['Drive!','Fly!']){if(!(await act(mode)))throw new Error('no '+mode+': '+await pg.evaluate(()=>[...document.querySelectorAll('#actions .act')].map(b=>b.textContent.trim()).join('|')));if(mode==='Drive!'){await W(3000);await pg.evaluate(()=>{window.__driveTo(29.76,-95.37);return window.__startRoadMission();});}let seen=0;for(let i=0;i<5;i++){await W(1000);const b=await boxes();if(i===0||i===3)await S('hud_'+mode.replace('!','')+i);
  const [H,Wd,pill]=await pg.evaluate(()=>[innerHeight,innerWidth,document.querySelector('#pill').textContent]);console.log(mode,i,pill);for(const k of ['#goalchip','#flyhint'])if(b[k]){if(H>Wd&&b[k].b>H*.5)throw new Error(k+' over the road at '+JSON.stringify(b[k]));for(const o of ['#caption','#minimap','#pill','#tstars','#bottom','#goalchip','#flyhint'])if(o!==k&&hit(b[k],b[o]))throw new Error(k+' overlaps '+o+' in '+mode);}
  if(b['#goalchip'])seen++;if(i===0)console.log(mode,JSON.stringify(b));}if(mode==='Drive!'&&!seen)throw new Error('goal chip never showed');
  await act(mode==='Drive!'?'Stop driving':'Stop flying');await W(400);await act('Tap again');await W(2500);}};
