// Ladder screens on a small phone: every sentence card (stages A-D) fits on screen; the number line hides its wrong choices; Level up shows on screen.
module.exports=async({pg,S,W,visit})=>{await pg.setViewportSize({width:360,height:640});await W(1000);const act=t=>pg.evaluate(t=>{const b=[...document.querySelectorAll('#actions .act')].find(b=>b.textContent.includes(t));b&&b.click();return !!b;},t);
await pg.click('#go');await W(1500);await pg.click('.th[data-id="earth"]');await W(2500);if(await pg.isVisible('.th[data-id="earth"]'))await pg.click('.th[data-id="earth"]');await W(11000);
await pg.click('#actions >> text=Places');await W(14000);await visit('college');await W(22000);if(!(await act('Number Lab')))throw new Error('no lab');await W(3000);
await pg.evaluate(()=>{localStorage.setItem('ast-ladder',JSON.stringify({numline:{r:0,s:2,h:[1,1]}}));window.__itemShow('numline',false)});await W(1500);await S('l3_numline');
const n=await pg.evaluate(()=>window.__labNow());await pg.evaluate(id=>document.querySelector(`#qtray .pl[data-id="${id}"]`).click(),n.ans);await W(700);await S('l3_levelup');const lv=await pg.evaluate(()=>{const d=document.querySelector('.lvlup');return d&&d.textContent});console.log('level badge',lv);if(!/Level 2/.test(lv||''))throw new Error('no Level up badge on screen');const nl=await pg.evaluate(()=>document.querySelectorAll('.nl .blank').length);
const over=[];await act('Back to campus');await W(2500);await act('Reading Room');await W(3000);
for(const st of [0,1,2,3])for(let j=0;j<3;j++){await pg.evaluate(r=>{localStorage.setItem('ast-ladder',JSON.stringify({sentence:{r,s:0,h:[]}}));window.__itemShow('sentence',true)},st);await W(700);const o=await pg.evaluate(()=>[...document.querySelectorAll('#qtray .pl')].map(b=>{const r=b.getBoundingClientRect(),h=b.querySelector('.hem');return [r.right>innerWidth+1||r.left<-1, h&&h.scrollWidth>b.clientWidth+1]}).filter(x=>x[0]||x[1]).length);if(o)over.push(st+':'+j);if(j===0)await S('l3_sent'+st);}
console.log('sentence overflow',JSON.stringify(over));if(over.length)throw new Error('sentence cards overflow: '+over.join(','));await pg.evaluate(()=>localStorage.removeItem('ast-ladder'));};
